apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "octopub.fullname" . }}
  labels:
    {{- include "octopub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "octopub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "octopub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "octopub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            {{- if .Values.productEndpointOverride }}
            - name: UDL_SETVALUE[/usr/share/nginx/html/config.json][productEndpoint]
              value: {{ .Values.productEndpointOverride }}
            {{- end -}}
            {{- if .Values.productHealthEndpointOverride }}
            - name: UDL_SETVALUE[/usr/share/nginx/html/config.json][productHealthEndpoint]
              value: {{ .Values.productHealthEndpointOverride }}
            {{- end -}}
            {{- if .Values.auditsEndpointOverride }}
            - name: UDL_SETVALUE[/usr/share/nginx/html/config.json][auditEndpoint]
              value: {{ .Values.auditsEndpointOverride }}
            {{- end -}}
            {{- if .Values.auditsHealthEndpointOverride }}
            - name: UDL_SETVALUE[/usr/share/nginx/html/config.json][auditHealthEndpoint]
              value: {{ .Values.auditsHealthEndpointOverride }}
            {{- end -}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
