name: Windows Exe Build and Push
description: Build the Java microservice
inputs:
  run_number:
    required: true
    description: The GitHub Actions Workflow run number
  github_repo:
    description: 'The github repo'
    required: true
  github_token:
    description: 'The github token'
    required: true
  aws_access_key:
    description: 'The aws access key'
    required: true
  aws_secret_access_key:
    description: 'The aws secret access key'
    required: true
  service_directory:
    description: 'The directory holding the microservice'
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone code repo
      uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: 5.x

    - id: determine_version
      name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        additionalArguments: /overrideconfig mode=Mainline

    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: adopt
        cache: 'maven'

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'

    - name: Install RSQL JPA
      run: ./mvnw --batch-mode install -DskipTests
      shell: powershell
      working-directory: java/rsql-jpa

    - name: Install modules
      run: ./mvnw --batch-mode install -DskipTests
      shell: powershell
      working-directory: java

    - name: Build and deploy Windows exe
      run: ./mvnw --batch-mode package -P "native" "-DskipTests" "-Dquarkus.profile=mysql"
      shell: powershell
      working-directory: java/${{ inputs.service_directory }}