apiVersion: v1
kind: Service
metadata:
  name: octopub-audit-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: auditservice
  ports:
    - port: 10000
      targetPort: 10000
      name: http-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopub-audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auditservice
  template:
    metadata:
      labels:
        component: auditservice
    spec:
      containers:
        - name: auditservice
          image: octopussamples/octopub-audit-microservice-mysql
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-password
            - name: DATABASE_HOSTNAME
              value: "192.168.1.64"
            - name: DATABASE_PORT
              value: "30000"
            - name: DATABASE_NAME
              value: "octopub_Development"
            - name: DATABASE_USERNAME
              value: "root"
            - name: MIGRATE_AT_START
              value: "false"
            - name: COGNITO_DISABLE_AUTH
              value: "false"