databaseType = "MySql"
id = "240efcf9-0b18-44d8-b484-10b4b5a2a99f"
name = "Octo-MySQL"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.development]
url = "jdbc:mysql://localhost:3306/octopubdev?allowPublicKeyRetrieval=true"
schemas = [ "octopubdev" ]
displayName = "Development database"

[environments.shadow]
url = "jdbc:mysql://localhost:3306/octopub_shadow?allowPublicKeyRetrieval=true"
schemas = [ "octopub_shadow" ]
displayName = "Shadow database"
provisioner = "clean"
