databaseType = "MySql"
id = "240efcf9-0b18-44d8-b484-10b4b5a2a99f"
name = "Octo-MySQL"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.development]
url = "jdbc:mysql://localhost:3306/sakila?allowPublicKeyRetrieval=true"
schemas = [ "octopubdev" ]
displayName = "Development database"
