-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Dropping underwatervr...
DROP TABLE underwatervr;


-- deployment: Dropping octomysql...
DROP TABLE octomysql;


-- deployment: Dropping auditors.Address...
ALTER TABLE auditors DROP COLUMN Address;

