<<<<<<< HEAD
-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Dropping octomysql...
DROP TABLE octomysql;
=======
-- Script generated by Redgate Compare v1.19.7.13456


-- deployment: Dropping metaversebookshop...
DROP TABLE metaversebookshop;
>>>>>>> 21acd7efcb1ddee9b93f82b8473698632f02751e

