-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Dropping gsutable...
DROP TABLE gsutable;


-- deployment: Creating vrbookstore...
CREATE TABLE vrbookstore (
    Author varchar(100) NULL,
    BookName varchar(100) NULL,
    Price varchar(100) NULL
);


-- deployment: Creating summit...
CREATE TABLE summit (
    Speakers varchar(100) NULL,
    Attendees varchar(100) NULL
);


-- deployment: Creating metaversebookshop...
CREATE TABLE metaversebookshop (
    Book varchar(100) NULL,
    Author varchar(100) NULL
);


-- deployment: Creating addressbook...
CREATE TABLE addressbook (
    FirstName varchar(100) NULL,
    LastName varchar(100) NULL,
    StreetAddress varchar(100) NULL
);

