-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Creating gsutable...
CREATE TABLE gsutable (
    Test1 varchar(100) NULL
);


-- deployment: Dropping product.Books...
ALTER TABLE product DROP COLUMN Books;

