-- Script generated by Redgate Compare v1.21.3.23074


-- deployment: Dropping underwatervr...
DROP TABLE underwatervr;


-- deployment: Dropping product.Underwater...
ALTER TABLE product DROP COLUMN Underwater;

