-- Script generated by Redgate Compare v1.21.2.23000


-- deployment: Creating movies...
CREATE TABLE movies (
    id int NOT NULL,
    title varchar(255) NOT NULL,
    director varchar(255) NULL,
    release_year year NULL,
    genre varchar(100) NULL,
    rating decimal(3,1) NULL
);
ALTER TABLE movies ADD PRIMARY KEY (id);

