-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Dropping gsutable...
DROP TABLE gsutable;


-- deployment: Creating product.Books...
ALTER TABLE product ADD COLUMN Books varchar(100) NULL;

