<<<<<<< HEAD
-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Creating octomysql...
CREATE TABLE octomysql (
    Test varchar(100) NULL
=======
-- Script generated by Redgate Compare v1.19.7.13456


-- deployment: Creating metaversebookshop...
CREATE TABLE metaversebookshop (
    Book varchar(100) NULL,
    Author varchar(100) NULL
>>>>>>> 21acd7efcb1ddee9b93f82b8473698632f02751e
);

