-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Creating underwatervr...
CREATE TABLE underwatervr (
    BookName varchar(100) NULL,
    UnitPrice varchar(100) NULL,
    Stock varchar(100) NULL
);


-- deployment: Creating octomysql...
CREATE TABLE octomysql (
    Test varchar(100) NULL,
    Run varchar(100) NULL
);


-- deployment: Creating auditors.Address...
ALTER TABLE auditors ADD COLUMN Address varchar(100) NULL;

