<<<<<<< HEAD
﻿-- Script generated by Redgate Compare v1.21.2.23000


-- deployment: Creating movies...
CREATE TABLE movies (
    id int NOT NULL,
    title varchar(255) NOT NULL,
    director varchar(255) NULL,
    release_year year NULL,
    genre varchar(100) NULL,
    rating decimal(3,1) NULL
);
ALTER TABLE movies ADD PRIMARY KEY (id);
=======
<<<<<<< HEAD
-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Creating octomysql...
CREATE TABLE octomysql (
    Test varchar(100) NULL
=======
-- Script generated by Redgate Compare v1.19.7.13456


-- deployment: Creating metaversebookshop...
CREATE TABLE metaversebookshop (
    Book varchar(100) NULL,
    Author varchar(100) NULL
>>>>>>> 21acd7efcb1ddee9b93f82b8473698632f02751e
);
>>>>>>> 235e71dbc9f1d377a21f44c6b9d22c0851d23259

