-- Script generated by Redgate Compare v1.19.7.21913


-- deployment: Dropping vrbookstore...
DROP TABLE vrbookstore;


-- deployment: Dropping summit...
DROP TABLE summit;


-- deployment: Dropping metaversebookshop...
DROP TABLE metaversebookshop;


-- deployment: Dropping addressbook...
DROP TABLE addressbook;


-- deployment: Creating gsutable...
CREATE TABLE gsutable (
    Test1 varchar(100) NULL
);

