-- Script generated by Redgate Compare v1.21.3.23074


-- deployment: Creating underwatervr...
CREATE TABLE underwatervr (
    Book varchar(100) NULL,
    Stock varchar(100) NULL,
    UnitPrice varchar(100) NULL
);


-- deployment: Creating product.Underwater...
ALTER TABLE product ADD COLUMN Underwater varchar(100) NULL;

