name: Build Products
permissions:
  contents: write
  packages: write
'on':
  workflow_dispatch: {}
  push:
    paths:
      - '**/*'
      - '!.github/badges/*'
      - '!README.md'
      - '!python/**/*'

jobs:
# https://github.com/quarkusio/quarkus/issues/33030 needs to be fixed before Windows builds will work
#  build-windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Build Products Windows
#        uses: ./github/java-microservice-windows
#        with:
#          run_number: ${{ github.run_number }}
#          github_repo: ${{ github.repository }}
#          github_token: ${{ github.token }}
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          service_directory: products-microservice
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Products Microservice
        uses: ./github/java-microservice
        with:
          run_number: ${{ github.run_number }}
          github_repo: ${{ github.repository }}
          github_token: ${{ github.token }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          octopus_url: ${{ secrets.DSC_OCTOPUS_URL }}
          octopus_apikey: ${{ secrets.DSC_OCTOPUS_API }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          service_directory: products-microservice

      - name: Build Products Helm Chart
        uses: ./github/helm
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          chart_directory: octopub-products-mysql