name: Build Self Contained Image
permissions:
  contents: write
  packages: write
'on':
  workflow_dispatch: {}
  push:
    paths:
      - '**/*'
      - '!.github/badges/*'
      - '!README.md'
      - '!python/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code repo
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # The Docker image used to run workers
      - name: Build, tag, and push worker image to Dockerhub
        if: ${{ steps.branch-name.outputs.current_branch == 'main' }}
        run: |
          docker build -f docker/selfcontained/Dockerfile -t octopussamples/octopus-selfcontained .
          docker push octopussamples/octopus-selfcontained
        shell: bash